### ISSUE TITLE
etest.idr doesn't typecheck

### ISSUE THREAD

**Issue by corazza** [steshaw/idris-sdl2#4]
```
[jan@pc test]$ make
idris --build bitmap.ipkg
etest disabled due to non-termination in type checker.
idris --build etest.ipkg
idris --build events.ipkg
idris --build hello.ipkg
idris --build test.ipkg
```

and

```
[jan@pc test]$ idris --build etest.ipkg 
Type checking ./etest.idr


etest.idr:128:8-136:20:
    |
128 | main = runInit [SDL2 (),
    |        ~~~~~~~~~~~~~~~~~ ...
When checking right hand side of main with expected type
        IO ()

Can't find implementation for Handler eff IO
```

The first `make` runs for a couple of seconds, while the individual `idris --build etest.ipkg` ran for ~2 mins, so I suspect that the error message about the handler implementation might actually be false, with something else being the underlying issue.

**Comment by steshaw** [comment]
Hi Jan, `etest` was disabled because of a known problem with the Idris compiler. I think what's confusing is that the `test/Makefile` echos the command that it doesn't run i.e. `idris --build etest.ipkg`. [See here](https://github.com/steshaw/idris-sdl2/blob/227678d921f29922ccb5ac458d760a6f1892eb77/test/Makefile#L10-L13).

I raised this issue with Edwin when I [made a pull request against his SDL1 bindings](https://github.com/edwinb/SDL-idris/pull/12) to upgrade to an older version of Idris. I also raised the issue on the Idris issue tracker but, unfortunately, it's not been addressed (that issue is linked from the pull request above). The Idris project is buried in issues. I await Blodwen. Love live Idris 😀.

I'll alter `Makefile` to make it more obvious that `idris --build etest.ipkg` isn't actually executed.

**Comment by corazza** [comment]
Thanks for the elaboration! I'm trying to make a game to get a better practical grip over Idris and it's not easy at all lol. Especially due to the error messages not always being the most welcoming to someone who doesn't already know what they mean.
